name: 'technical_challenge'
version: '1.0.0'
config-version: 2
profile: 'technical_challenge'

model-paths: ["models"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  +materialized: table
  technical_challenge:
    +materialized: table
